services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    environment:
      - PUID=1000
      - PGID=999 # docker group id
      - HOMEPAGE_ALLOWED_HOSTS=home.soylu.uk
    ports:
      - 3000:3000
    volumes:
      - ${DataRootPath:-..}/config/homepage:/app/config # Make sure your local config directory exists
      - /var/run/docker.sock:/var/run/docker.sock:ro # optional, for docker integrations
    restart: unless-stopped

  pihole: # More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
    container_name: pihole
    image: pihole/pihole:latest
    # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
    ports:
      - "${InternalIP:-}:53:53/tcp"
      - "${InternalIP:-}:53:53/udp"
      # - "67:67/udp" # Only required if you are using Pi-hole as your DHCP server
      - "8081:80/tcp"
    environment:
      TZ: 'Central European Time'
      WEBPASSWORD: '${WebPassword:-}'
    # Volumes store your data between container upgrades
    volumes:
      - '${DataRootPath:-..}/config/pihole/etc-pihole:/etc/pihole'
      - '${DataRootPath:-..}/config/pihole/etc-dnsmasq.d:/etc/dnsmasq.d'
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    restart: unless-stopped

# https://hub.docker.com/_/caddy
  caddy:
    build:
      context: .
      dockerfile: CaddyCloudflareDockerfile
    container_name: caddy
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    environment:
      - CF_API_TOKEN # workaround for env. variable won't pass to the container. https://github.com/portainer/portainer/issues/10491#issuecomment-2192819975
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ${DataRootPath:-..}/config/caddy/Caddyfile:/etc/caddy/Caddyfile
      - ${DataRootPath:-..}/config/caddy/site:/srv
      - ${DataRootPath:-..}/config/caddy/data:/data
      - ${DataRootPath:-..}/config/caddy/config:/config
