---
version: "2.1"
services:
  calibre:
    image: lscr.io/linuxserver/calibre:latest
    container_name: calibre
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Istanbul
      - PASSWORD= #optional
      - CLI_ARGS= #optional
    volumes:
      - ./data/calibre/config:/config
    ports:
      - 8090:8080
      - 8091:8081
    restart: unless-stopped

