---
# Development Stack

version: '3.3'
services:
  MySQL57:
    image: mysql:5.7
    restart: unless-stopped
    container_name: MySQL57
    environment:
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'somepassword1!'
      MYSQL_ROOT_PASSWORD: 'somepassword1!'
    ports:
      - '3306:3306'
    volumes:
      - ${DataRootPath:-.}/data/mysql:/var/lib/mysql
