# Development Stack
services:
  Redis:
    image: redis/redis-stack-server:latest
    restart: unless-stopped
    container_name: Redis
    ports:
      - '6379:6379'
    stdin_open: true 
    tty: true

  MSSQL2022:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: unless-stopped
    container_name: MSSQL2022
    environment:
      ACCEPT_EULA: 'Y'
      MSSQL_SA_PASSWORD: ${MSSQL_PASSWORD}
    ports:
      - '1433:1433'
    volumes:
      - ${DataRootPath:-.}/data/mssql:/var/opt/mssql/data

  PostgreSQL:
    image: postgres:latest
    restart: unless-stopped
    container_name: PostgreSQL
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ${DataRootPath:-.}/data/postgresql:/var/lib/postgresql/data 
