---
# Development Stack

version: '3.3'
services:
  MySQL57:
    image: mysql:5.7
    restart: unless-stopped
    container_name: MySQL57
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ROOT_HOST: '%'
    ports:
      - '3306:3306'
    volumes:
      - ${DataRootPath:-.}/data/mysql:/var/lib/mysql
      
  Redis:
    image: redis/redis-stack-server:latest
    restart: unless-stopped
    container_name: Redis
    environment:
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'somepassword1!'
      MYSQL_ROOT_PASSWORD: 'somepassword1!'
    ports:
      - '6379:6379'
    stdin_open: true 
    tty: true
