---
# Development Stack

version: "3"
services:
  jenkins:
    image: jenkins/jenkins:latest
    privileged: true
    user: root
    ports:
      - 8090:8080
      - 50000:50000
    restart: unless-stopped
    container_name: jenkins
    volumes:
      - ${DataRootPath:-.}/data/jenkins/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

  selenium:
    image: selenium/standalone-chrome:latest
    ports:
      - 4444:4444
      - 7900:7900
    container_name: selenium
    restart: unless-stopped
