---
# Development Stack

version: '3.3'
services:

  MySQL57:
    image: mysql:5.7
    restart: unless-stopped
    container_name: MySQL57
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ROOT_HOST: '%'
    command: mysqld --sql_mode="STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
    ports:
      - '3306:3306'
    volumes:
      - ${DataRootPath:-.}/data/mysql:/var/lib/mysql
      
  Redis:
    image: redis/redis-stack-server:latest
    restart: unless-stopped
    container_name: Redis
    ports:
      - '6379:6379'
    stdin_open: true 
    tty: true

  MSSQL2022:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: unless-stopped
    container_name: MSSQL2022
    environment:
      ACCEPT_EULA: 'Y'
      MSSQL_SA_PASSWORD: 'SomeRandom1!'
    ports:
      - '1433:1433'
    volumes:
      - ${DataRootPath:-.}/data/mssql:/var/opt/mssql/data
