---
version: "2.1"
services:
  plex:
    image: lscr.io/linuxserver/plex
    container_name: plex
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - PLEX_CLAIM= #optional
      - ALLOWED_NETWORKS=192.168.0.0/16,172.0.0.0/8
    volumes:
      - ./data/plex/library:/config
      - ./data/qbittorrent/downloads/series:/tv
      - ./data/qbittorrent/downloads/movies:/movies
    restart: unless-stopped
    ports:
      - 32400:32400
      - 1901:1900/udp
      - 3005:3005
      - 5354:5353/udp
      - 8324:8324
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
      - 32469:32469
