---
version: "2.1"
services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./data/radarr/config:/config
      - ./data/qbittorrent/downloads/movies:/movies #optional
      - ./data/qbittorrent/downloads:/downloads #optional
    ports:
      - 7878:7878
    restart: unless-stopped
